### ISSUE TITLE
IP is local IP address

### ISSUE THREAD

**Issue by OneMoreByte** [ElegantDestruction/DNS_Updater#2]
OOF, so the ip is the local IP address, good thing my home ip is memorable. We should probably fix that so it works outside of a certain goofily set up network.

**Comment by jahillebrand** [comment]
Alright so I fixed the IP address error, but now I'm getting a type error when I try to run the full script I get a type error as follows:
No previous ip.
Updating jakehill.jackhil.de with new IP b'144.13.213.61'.
Traceback (most recent call last):
  File "./dns_updater.py", line 82, in <module>
    main()
  File "./dns_updater.py", line 74, in main
    update_dns(domain.strip(), ip)
  File "./dns_updater.py", line 32, in update_dns
    'Value': ip
  File "/home/exposedbuckle48/.local/lib/python3.5/site-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/exposedbuckle48/.local/lib/python3.5/site-packages/botocore/client.py", line 596, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/home/exposedbuckle48/.local/lib/python3.5/site-packages/botocore/client.py", line 632, in _convert_to_request_dict
    api_params, operation_model)
  File "/home/exposedbuckle48/.local/lib/python3.5/site-packages/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter ChangeBatch.Changes[0].ResourceRecordSet.ResourceRecords[0].Value, value: b'144.13.213.61', type: <class 'bytes'>, valid types: <class 'str'>

I'm not sure if this wasn't an error before I changed anything or not
